version: '2.1'

services:
  web:
    build: ./flask
    container_name: flask_web
    command: python run.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - mariadb
    expose:
      - 8080

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/Madrid
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/config
    ports:
          - 3306:3306
    restart: unless-stopped


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
    mariadb_data: